name: mi_fortitu
description: "A Flutter app for 42 students"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  app_links: ^6.4.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.7
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  mocktail: ^1.0.4
  oauth2: ^2.0.3
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/gif/
    - assets/images/home_tiles/
    - assets/translations/
    - test/resources/
    - assets/campus_layouts/



